### ISSUE TITLE
decide on # of hotel hours correct

### ISSUE THREAD

**Issue by binary1230** [magfest/magclassic#23]
is it 24 hours gets you a room, or 30?

depending on which, this text here may need to be updated:

```
What You Get For Volunteering

The more hours you work, the more you get (don't forget about weighted hours):
Working at least 6 hours gets you a MAGFest Laboratories t-shirt. 

Working at least 12 hours gets you food in addition to the shirt. We have professional chefs preparing 3 meals per day throughout the event. 

Working at least 18 hours gets you a complementary Staff badge for next year's MAGFest Laboratories, which will make you eligible for space in one of our staff hotel rooms. 

Working at least 24 hours gets you a refund on your badge for this year. 

Working at least 30 hours ONLY IF you're a returning Staffer gets you space in one of our staff hotel rooms. 
```

also set c.HOTEL_REQ_HOURS in the hotel plugin

**Comment by bds002** [comment]
This is up to the RT, but the conversation we had last year was that since the Fall event was a day less than Fest, we edited the hours down a bit from 30.

**Comment by binary1230** [comment]
OH HEY, realized, on our staging server, the hotel plugin is not yet enabled.  The hotel plugin overrides this text, so, once we turn it on, this text will drop the hours back to 24.

**Comment by binary1230** [comment]
current text ```Working at least 24 hours ONLY IF you're a returning Staffer gets you space in one of our staff hotel rooms.```

**Comment by bds002** [comment]
RT approves this change, 24 instead of 30 because of a shorter event - consistent with MClassic in 2015

**Comment by bds002** [comment]
Although we might want to look at:
Working at least 18 hours gets you a complementary Staff badge for next year's MAGFest Laboratories, which will make you eligible for space in one of our staff hotel rooms. 

Do we need to edit this to say - you would would be eligible for a staff badge at the next MAGFest event
Labs volunteers that meet this threshold would get imported to MAGFest Super event even if we don't do another fall event...

**Comment by kitsuta** [comment]
@jcooter approves closing this.
