### ISSUE TITLE
add parental consent form URL for maglabs, or disable it

### ISSUE THREAD

**Issue by binary1230** [magfest/magclassic#25]
currently points to 
http://magfest.org/minorconsentform

which has gaylord-version only

may need to modify it (the original .doc is floating around somewhere) and make a markcenter-specific version.  or talk to reg/RT/BOD and figure out if this is something we still are doing for maglabs.

**Comment by kitsuta** [comment]
Disabled by https://github.com/magfest/production-config/pull/42.
