### ISSUE TITLE
clicking group reg button says "group reg closed"

### ISSUE THREAD

**Issue by binary1230** [magfest/magclassic#27]
on labs prereg page click button 'Group Leader' for registration type.

expected: you can register for a group badge 

actual:
![image](https://cloud.githubusercontent.com/assets/5413064/15228600/f5b67f74-185a-11e6-81d3-0c1439fa918e.png)

notes:
in preregbase.html, ```{% if c.BEFORE_GROUP_REG_TAKEDOWN %}``` is false, causing the error.  WEIRDLY, I can't find a reference to GROUP_REG_TAKEDOWN anywhere in the code or INI settings, so... not sure what is supposed to be going on here.

**Comment by kitsuta** [comment]
Unrelated to everything: Why does that bar look so much better, who fixed that and when

**Comment by earl7399** [comment]
+1

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
