### ISSUE TITLE
hardcoded stuff: dates and 'magclassic'

### ISSUE THREAD

**Issue by binary1230** [magfest/magclassic#28]
@bds002 was interested in taking on this.

lots of places in the magclassic plugin hardcode the following stuff:
- last year's dates (sept 11th to 13th) should be (sept 9th to 11th)
- last year's event name (magclassic) should be (maglabs)

Almost too much to list individually, needs a major scrub of everything in magclassic plugin.

[ ] magclassic/templates/regextra.html
[ ] imported_volunteers.txt

**Comment by kitsuta** [comment]
Should be fixed by #30.
