### ISSUE TITLE
confirmation email: badge transfer date is mid-event

### ISSUE THREAD

**Issue by binary1230** [magfest/magclassic#29]
c.UBER_TAKEDOWN date needs to be chosen carefully here because it affects badge transferring.

```To transfer your registration to another person, send them this personalized link, which will work until 11:59pm EDT on Saturday, Sep 10.```

sidenote: should we think about decoupling uber_takedown from the badge transfer deadline?

**Comment by thaeli** [comment]
Upstream perspective:
![image](https://cloud.githubusercontent.com/assets/384634/15230447/e8da29b6-1852-11e6-9119-ea99fa8a53b5.png)

Seriously, yeah, I can see other events where these would definitely be very different dates.

**Comment by kitsuta** [comment]
For the zillionth time:

`c.UBER_TAKEDOWN` _does not actually do anything._ It is TEXT configuration. Nothing more.

I would like to get rid of it, though.
