### ISSUE TITLE
Date is incorrect in Attending field

### ISSUE THREAD

**Issue by StephPrader** [magfest/magclassic#35]
![screen shot 2016-06-03 at 10 10 26 am](https://cloud.githubusercontent.com/assets/8381162/15781323/9c27e5a4-2973-11e6-9fec-595407a63a35.png)

It should be 9-11, not 11-13.

**Comment by StephPrader** [comment]
er, maybe 9th-11th. for sanity.

**Comment by binary1230** [comment]
having a suprising time trying to track this down

**Comment by binary1230** [comment]
lies. it's hardcoded in magclassic plugin regextra.html, fixing...
