### ISSUE TITLE
MAGLabs logo size is hard-coded and thus nonresponsive

### ISSUE THREAD

**Issue by kitsuta** [magfest/magclassic#37]
The logo is too big on mobile because its size is explicitly set in CSS, overriding Bootstrap's responsive goodness.

![image](https://cloud.githubusercontent.com/assets/7198215/15790571/040ad4f2-29a0-11e6-897a-2f3b27147b1c.png)

**Comment by jcooter** [comment]
This is still an issue.

**Comment by RobRuana** [comment]
Done and done. Forgot to close the issue :)
