### ISSUE TITLE
Marketplace Tables not showing on application review screen

### ISSUE THREAD

**Issue by bds002** [magfest/magclassic#41]
As reported by @Shanezilla
Reviewing two pages in regards to groups and Marketplace tables....

(1) On: https://staging2.uber.magfest.org/uber/groups/

![groups_listing](https://cloud.githubusercontent.com/assets/8822346/16738935/d181b148-4765-11e6-8859-9c8de93255e9.PNG)

It shows the number of tables for each vendor/group

(2) Using MAGTest as an example:
When you load their individual page:
https://staging2.uber.magfest.org/uber/groups/form?id=20f457e8-872f-4f40-883a-c13dbe59b62d

It doesn't show the # of tables they have requested, it only shows their total group price.

![magtest_table](https://cloud.githubusercontent.com/assets/8822346/16739036/47ee8086-4766-11e6-8c91-5ae4f261c5e1.PNG)

-------
The application page (individual page) should show how many tables each vendor/group is requesting.

**Comment by binary1230** [comment]
in templates/groups/form.html the line that populates the table group is:
```
{% options c.ADMIN_TABLE_OPTS group.tables %}
```

so, something is going weird there where it's not selecting the correct item in the list to make it select '8' as the table count.

**Comment by binary1230** [comment]
chasing this down a bit.

fun fact, did you know that ```Group.tables``` is a float and not an int? ```tables        = Column(Float, default=0)```

**Comment by binary1230** [comment]
yea that's gotta be it.  this line in custom_tags.py decides whether to mark something in the dropdown list as 'selected' or not:

```selected = 'selected="selected"' if str(val) == str(default) else ''```

Suppose this group has 2 tables.  ```default``` will be the currently selected value of 2, and when we are iterating over the list of values in the dropdown, which is [0,1,2,3,4,5,6,7,8], we should mark 2 as 'selected'.

In our case, ```str(val)``` is ```'2'``` (an int), while str(default) is ```'2.0'``` which is a float.

I think the right answer here is to change:

```tables = Column(Float, default=0)```
to
```tables = Column(Int, default=0)```

Unless there's some compelling reason to keep it as a float.  (half tables? but they can't be selected soo... not sure that's a valid thing)

**Comment by binary1230** [comment]
And to be clear, the error is that '2' should be selected, but it's not because the strings '2.0' and '2' are obviously not identical strings.

**Comment by earl7399** [comment]
Half tables are a thing, IIRC. Need to loop in Marketplace.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
so I know that we do half tables but, is there anywhere in the UI where you can type in the number vs picking an integer from the dropdown box?  if there is and we legit use half tables *in uber* then I guess we do need to make that work.

In that case, we can probably cast group.tables to int either in python or in the template, and then use that in the {% options %} tag

**Comment by binary1230** [comment]
yea doesn't look like there's anywhere in the UI where you can type non-integer amount of tables, looks just to be something we overlooked until now.  the column was set to Float 2 years ago in the sqlalchemy migration

**Comment by kitsuta** [comment]
No, I think it should be kept as a float in the database. We can easily typecast the float to an int before converting it into a string if necessary, but more likely the solution is just to make ADMIN_TABLE_OPTS a list of floats.

**Comment by thaeli** [comment]
Floats kinda scare me from a data Integrity perspective. (Rounding bad!) Is
there a way we could rethink half tables so that an integer could be used?
Semi serious suggestion: millitables as a unit. Or maybe use a fixed-point
fractional number?

**Comment by kitsuta** [comment]
That can be done, though it's out of scope for fixing this particular issue. Fixed-point may not work so well since there's a chance that some event somewhere will want to sell quarter-tables, so maybe we will do some math on millitables.
