### ISSUE TITLE
Unassigning a badge in dealer's group increased the amount owed

### ISSUE THREAD

**Issue by earl7399** [magfest/magclassic#52]
PAID Dealer group w/1 table, 3 badges - all assigned. Unassigned 1 badge, amount owed got bumped by $15

**Comment by jcooter** [comment]
This issue still exists.

**Comment by kitsuta** [comment]
Testing update: this happens because unassigning the badge removes its Shopkeep ribbon. The pricing code works as expected -- it's the fact that we remove the ribbon that causes us to charge the badge as full-price instead of dealer-price.
