### ISSUE TITLE
Remove staff suite references

### ISSUE THREAD

**Issue by jcooter** [magfest/magclassic#64]
We're not going to be serving food in staff suite this year due to budget problems.  All references to food service for labs need to be removed.

**Comment by BlueHat-GURU** [comment]
Closed by https://github.com/magfest/production-config/issues/200 ?

**Comment by RobRuana** [comment]
There is still one outstanding pull request in the ubersystem repo that needs to be merged to close this issue. There is a small change request pending that is preventing the pull request from being merged. 

See: https://github.com/magfest/ubersystem/pull/2428

**Comment by BlueHat-GURU** [comment]
Ah. What I'm seeing is showing the merge as successful. Interesting.

**Comment by RobRuana** [comment]
GitHub is really neat, because it tells you before the merge is performed if the merge _would be_ successful. At first glance that could easily be read as "the merge _was_ successful" 😄

**Comment by kitsuta** [comment]
I think Dave is referring to the fact that several PRs reference this issue and they HAVE been merged. There's still one with the "Open" tag, however, and that's the one waiting on requested changes (and my bad for not getting to it in a timely manner -- I'll do it first thing on Monday).

**Comment by BlueHat-GURU** [comment]
Oh, cool!
