### ISSUE TITLE
Fancy supporter levels doesn't appear on the pre-reg page

### ISSUE THREAD

**Issue by jcooter** [magfest/magclassic#67]
There are currently 4 supporter tiers configured for labs:

`uber::config::donation_tier:
 No thanks: 0
 Shirt: SHIRT_LEVEL
 Supporter Pack: SUPPORTER_LEVEL
 Super Supporter: 170

uber::config::donation_tier_descriptions:
  no_thanks:
    name: "No thanks"
    icon: ""
    description: "No thanks"
    link: ""
  shirt:
    name: "Shirt"
    icon: "../static/icons/iconshirt.png"
    description: "Ribbon|T-Shirt"
    link: "../static_views/ribbon.html|../static_views/tshirt.html"
  supporter_pack:
    name: "Supporter Pack"
    icon: "../static/icons/heart-necklace.png"
    description: "Upgraded electronic badge|Swag Bag"
    link: ""
  super_supporter:
    name: "Super Supporter"
    icon: "../static/icons/menace.png"
    description: "More upgraded electronic badge|Something else"
    link: ""`

The pre-reg page currently only shows the first three options, and doesn't include the new fancy swag display that super 2017 had.

Curiously, the reg confirmation page *does* include the new view, though the icons and links are broken (which is expected, they are copy pasta from the super config).

**Comment by binary1230** [comment]
If I remember correctly, there's a config option to toggle between fancy
and non fancy, and there might be some interaction with overrides in the
magprime plugin

Note that way the HTML formatting/styling for the fancy display works is
pretty fragile so definitely test any changes heavily here

**Comment by binary1230** [comment]
following up, here's the line that determines fancy vs non-fancy:
https://github.com/magfest/ubersystem/blob/master/uber/templates/regform.html#L198

if  c.PREREG_DONATION_DESCRIPTIONS exists, it'll do the fancy stuff.

**Comment by kitsuta** [comment]
If the reg confirmation page shows the new options, then it's pretty clear that this config option is already set correctly. Something else on the prereg page itself must be interfering.

**Comment by binary1230** [comment]
to also turn this on you may need this line of code, not 100% sure (it was switched on for magprime) : https://github.com/magfest/magprime/blob/master/magprime/templates/regextra.html#L54

(trying to braindump stuff so you guys don't need to go off on a wild goose chase)

**Comment by binary1230** [comment]
final note and I will resume lurking here :) 

the UI for the fancy supporter tiers is pretty jank (we did it in a hurry last year) and has a bunch of inline CSS and hardcoded sizes and such.  It might still be ok, just, if you change other stuff it might break.  I was tracking that in https://github.com/magfest/ubersystem/issues/2382
