### ISSUE TITLE
fix registration.py

### ISSUE THREAD

**Issue by binary1230** [magfest/magclassic#80]
```magclassic/site_sections/registration.py``` can't be named that because it's overriding everything in the underlying plugin (the 'registration' pages are the backend attendee edit pages)

should probably just revert https://github.com/magfest/magclassic/pull/78/files

rename 'registration.py' to be 'reg_stats.py' or something like that, and should be ok.

would also suggest this either go into the 'uber_analytics' plugin on the generic 'magfest' plugin

**Comment by binary1230** [comment]
high priority cause our admin pages be borked currently

**Comment by kitsuta** [comment]
I've already deployed the revert to prod.

**Comment by RobRuana** [comment]
It's intentionally in magclassic because that page hammers the server and I didn't want it in main uber.

**Comment by kitsuta** [comment]
Agreed, we don't want this in main MAG or people will constantly refresh it right during the rush and then everyone will be very sad.
